### ISSUE TITLE
Questions understanding your code and using your software

### ISSUE THREAD

**Issue by botsneedjuice** [hasherezade/dll_to_exe#3]
Hello @hasherezade ,
I'm a new GitHub user with little to no C++ programming xp. i need to convert a native .dll file into a .exe. In the file finder, there are numerous files (i.e pe_handler.cpp, main.cpp, CMakeLists.txt e.t.c) with varying codes. What does each file do?
If you're free can you walk me through the process on how to convert my native .dll file to .exe like you'd a 13 yr old kid? Thanks

**Comment by hasherezade** [comment]
Hi!
You don't have to build the project by youself to be able to use it. There are ready made builds available here:
https://github.com/hasherezade/dll_to_exe/releases
Just download `dll_to_exe.exe`, and then run it.

**Comment by botsneedjuice** [comment]
Oh great!, thanks for responding i was able to dl it.
